export const legacyTimeline = [
	{ year: '1970s', title: 'The journey began with the establishment of the first sleeper manufacturing unit, laying the foundation for what would become one of India\'s largest railway infrastructure companies.', side: 'right' as const },
	{ year: '1980s', title: 'Early adoption by Indian Railways marked this decade, as the company expanded its reach into new railway zones, building trust and scale in the sector.', side: 'left' as const },
	{ year: '1990s', title: 'The Kargi Road plant was commissioned, a milestone that strengthened operations. This period also saw the introduction of in-house R&D and modular track systems. A landmark achievement came with the KRCL Mumbai project, supplying over 20 lakh sleepers, followed by the establishment of the Madurai unit, further expanding the company\'s manufacturing footprint.', side: 'right' as const },
	{ year: '2000s', title: 'The Kaipadar unit was taken over, and the Nagpur plant was relocated to Anara, consolidating the production base. This decade also saw the company enter the urban rail and metro segment while developing turnkey project capabilities. Over 1 lakh sleepers were supplied to Bangladesh.', side: 'left' as const },
	{ year: '2010s', title: 'The company secured approvals for high-speed and freight corridors, significantly widening its scope. Exports expanded with sleepers supplied to Sri Lanka. Insert manufacturing commenced at the foundry units and strategic acquisitions included Daya Engineering Works Private Limited and ICON Sleeper Track Private Limited further strengthened technical capacity.', side: 'right' as const },
	{ year: 'Early 2020s (2018-2021)', title: 'The early 2020s marked the rise of large-scale foundry operations. In 2018, the first foundry was set up at Kallakal, Hyderabad with a capacity of 4.5 lakh inserts per month, followed by DMRC getting the base plate production in 2019. In 2020, a second foundry was commissioned at Bokaro and Apna Technologies & Solutions was acquired, adding advanced rail track and condition monitoring expertise. By 2021, Bokaro began operations with 3.5 lakh inserts per month, while 20 new sleepers were exported to Sri Lanka.', side: 'left' as const },
	{ year: 'Late 2020s (2022-2024)', title: 'This phase was defined by expansion and operational milestones. In 2022, production began at the Medchal plant. By 2023, the Bokaro foundry reached 7 lakh inserts per month alongside the laying of 70 km zero tolerance track. In 2024, Kallakal also achieved 7 lakh inserts per month, new projects at Tumkur and Kovvur were launched, Indian Railways\' first W-beam fencing project was completed, and major DMRC fastening system contracts were secured.', side: 'right' as const },
	{ year: '2025', title: '2025 marked a new era of scale and diversification. The Bokaro foundry doubled capacity to 14 lakh inserts per month with a second production line, while Kallakal advanced into high-value manufacturing with railway-critical braking and suspension components. The year also saw the launch of Patil Labs (dedicated R&D), an expanded precast portfolio, and a wire drawing business at Chandrapur, positioning the company as a one-stop railway and infrastructure solutions provider.', side: 'left' as const },
];


